%% Transform LEMON dataset to BIDS format
%
% This script generates the BIDS sidecars of the the LEMON dataset.
% The file participants.json has to be created manually.
%
% Cristina Gil, 05.08.2022, Technical University of Munich

clear all;

% Add fieldtrip
addpath /rechenmagd4/toolboxes_and_functions/fieldtrip
ft_defaults

dataset_name = 'LEMON-8min';
    
% Specify the folders with the original data and the output directory
dir_in = '/rechenmagd4/Experiments/2021_preprocessing/datasets/LEMON-5min';
dir_out = '/rechenmagd4/Experiments/2021_preprocessing/datasets/LEMON-5min-bids';
files = dir(fullfile(dir_in,'sub-*'));

% Load participants' demographics
demo = readtable('Participants_MPILMBB_LEMON.csv');
demo.Properties.VariableNames = {'participant_id','sex','age_group'};
demo.participant_id = categorical(demo.participant_id); % Use categorical for accessing elements by category
%% Generate BIDS sidecar files (data2bids function)
% Important: participants.json has to be generated by hand

cfg = [];
cfg.method      = 'copy';
cfg.datatype    = 'eeg';
cfg.bidsroot    = dir_out;

% ======== INFORMATION DERIVED FROM THE PAPER Babayan et. al 2018 ========
% Datasate description (will be added to "dataset_description.json")
cfg.dataset_description.Name =                'LEMON-BIDS';

% Specific EEG info  (will be added to the "....eeg.json" file in the folder with the actual data)
cfg.Manufacturer                = 'Brain Products';
cfg.ManufacturersModelName      = 'BrainAmp MR';
cfg.eeg.EEGReference            = 'FCz';
cfg.eeg.PowerLineFrequency      = 50;
cfg.eeg.CapManufacturer         = 'ActiCAP';
cfg.eeg.EEGChannelCount         = 61;
cfg.eeg.EOGChannelCount         = 1;
cfg.eeg.ECGChannelCount         = 0;
cfg.eeg.MiscChannelCount        = 0;
cfg.eeg.TriggerChannelCount     = 0;
cfg.eeg.EEGGround               = 'sternum';
% =========================================================================
for iSubj=1:length(files)
       
    % Input EEG file
    cfg.dataset = fullfile(files(iSubj).folder,files(iSubj).name,'eeg',[files(iSubj).name '_eeg.vhdr']);
    cfg.sub = char(regexp(files(iSubj).name,'\d{6}','match'));
    
    % Information about the participants (added to participants.tsv)
    cfg.participants.sex          = demo{demo.participant_id == files(iSubj).name,'sex'};
    cfg.participants.age_group    = demo{demo.participant_id == files(iSubj).name,'age_group'};
    
    data2bids(cfg);
end
     

